server:
  port: 5100

spring:
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      group-id: habeebcycle-group-1
      auto-offset-reset: earliest

habeebcycle:
  kafka:
    topic: habeebcycle-topic-1